version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: transitpulse_db
      POSTGRES_USER: transitpulse_user
      POSTGRES_PASSWORD: transitpulse_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
