version: '3.8'
services:
  db:
    image: postgres:15
    container_name: transitpulse-db-1
    restart: unless-stopped
    environment:
      POSTGRES_DB: transitpulse_db
      POSTGRES_USER: transitpulse_user
      POSTGRES_PASSWORD: transitpulse_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transitpulse_user -d transitpulse_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata:
    driver: local
